# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20160907_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField()),
                ('valor_movimento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Investimento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='movimento',
            name='tipo_movimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.TipoMovimento'),
        ),
    ]
